name: my-workflow
on:
    push:
        paths:
            - "packages/web-client/**"
            - ".github/workflows/action-test.yml"
jobs:
    build:
        name: build
        defaults:
            run:
                working-directory: ./packages/web-client
        runs-on: ubuntu-latest
        steps:
            # ...
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.0.26

            # run any `bun` or `bunx` command
            - name: Install Dependencies
              run: bun install
            - name: Build
              run: bun run build

            # create artifact

            - uses: actions/upload-artifact@v4
              with:
                  name: dist-without-markdown
                  path: |
                      dist
                      !dist/**/*.md
    deploy:
        name: deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: dist-without-markdown
                  path: html
            - uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_SERVER }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  source: html/*
                  target: "/var/www/game.daltech.ca"
