name: my-workflow
on: [push]
jobs:
    my-job:
        name: my-job
        runs-on: ubuntu-latest
        steps:
            # ...
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.0.26 # or "latest", "canary", <sha>

            # run any `bun` or `bunx` command
            - run: bun install
            - run: bun run build
