name: my-workflow
on: [push]
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            # ...
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.0.26

            # run any `bun` or `bunx` command
            - run: bun install
            - run: bun run build

            # create artifact

            - uses: actions/upload-artifact@v4
              with:
                  name: dist-without-markdown
                  path: |
                      dist
                      !dist/**/*.md
    deploy:
        name: deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: dist-without-markdown
                  path: html
            - uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_SERVER }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  source: html/*
                  target: "/var/www/game.daltech.ca"
