name: my-workflow
on: [push]
jobs:
    my-job:
        name: my-job
        runs-on: ubuntu-latest
        steps:
            # ...
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.0.26 # or "latest", "canary", <sha>

            # run any `bun` or `bunx` command
            - run: bun install
            - run: bun run build
    deploy:
        name: deploy artifact
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - run: echo hello > world.txt

            - uses: actions/upload-artifact@v4
              with:
                  name: my-artifact
                  path: world.txt

            - uses: actions/download-artifact@v4
              with:
                  name: my-artifact
                  path: distfiles

            - name: copy file to server
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_SERVER }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  source: distfiles/*
                  target: "/var/www/game.daltech.ca"
