name: my-workflow
on: [push]
jobs:
    build:
        name: my-job
        runs-on: ubuntu-latest
        steps:
            # checkout
            - name: checkout
              uses: actions/checkout@v4

            # build
            - name: build
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.0.26 # or "latest", "canary", <sha>
              run: |
                  bun install
                  bun run build

            # create artifact
            - name: create build artifact
              uses: actions/upload-artifact@v4
              with:
                  name: dist-without-markdown
                  path: |
                      dist
                      !dist/**/*.md

            - name: download artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist-without-markdown
                  path: html

            - name: copy dist to server
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_SERVER }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  source: html/*
                  target: "/var/www/game.daltech.ca"
