name: my-workflow
on: [push]
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            # ...
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.0.26

            # run any `bun` or `bunx` command
            - run: bun install
            - run: bun run build

            # create artifact

            - uses: actions/upload-artifact@v4
              with:
                  name: dist-without-markdown
                  path: |
                      dist
                      !dist/**/*.md
