name: server
on:
    push:
        paths:
            - "packages/server/**"
            - ".github/workflows/server.yml"
jobs:
    build:
        name: build
        defaults:
            run:
                working-directory: ./packages/server
        runs-on: ubuntu-latest
        environment: production
        steps:
            # ...
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.0.33

            # run any `bun` or `bunx` command
            - name: Check ENV
              run: printenv
            - name: Install Dependencies
              run: bun install
            - name: Build
              run: bun run build

            # create artifact

            - uses: actions/upload-artifact@v4
              with:
                  name: server-dist-without-markdown
                  path: |
                      packages/server/dist
                      !packages/server/dist/**/*.md
    deploy:
        name: deploy
        needs: build
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Copy build
              uses: actions/download-artifact@v4
              with:
                  name: server-dist-without-markdown
                  path: app

            - name: Copy build to server
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_SERVER }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  source: app/*
                  target: "/var/www/gameserv.daltech.ca"

            - name: SSH Remote Commands
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_SERVER }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      sudo systemctl restart gameserv
                      systemctl status gameserv
